import type {
  BackgroundConfig,
  CardFontId,
  DesignState,
  DesignTemplate,
  TextStyle,
} from "@/types";

const solid = (
  color: string,
  extras: Partial<BackgroundConfig> = {},
): BackgroundConfig => ({
  kind: "solid",
  color,
  pattern: "none",
  texture: "none",
  customImage: null,
  imageZoom: 1,
  imageX: 50,
  imageY: 50,
  overlay: "#000000",
  overlayOpacity: 0,
  blur: 0,
  brightness: 100,
  ...extras,
});

const gradient = (
  color: string,
  secondaryColor: string,
  angle = 160,
  extras: Partial<BackgroundConfig> = {},
): BackgroundConfig => ({
  kind: "gradient",
  color,
  secondaryColor,
  gradientAngle: angle,
  pattern: extras.pattern ?? "none",
  texture: extras.texture ?? "none",
  customImage: null,
  imageZoom: 1,
  imageX: 50,
  imageY: 50,
  overlay: extras.overlay ?? "#000000",
  overlayOpacity: extras.overlayOpacity ?? 0,
  blur: extras.blur ?? 0,
  brightness: extras.brightness ?? 100,
  ...extras,
});

const typeStyle = (
  font: CardFontId,
  size: number,
  weight: number,
  color: string,
  extras: Partial<TextStyle> = {},
): TextStyle => ({
  font,
  size,
  weight,
  letterSpacing: extras.letterSpacing ?? 0,
  color,
  align: extras.align ?? "center",
  transform: extras.transform ?? "none",
});

export const templates: DesignTemplate[] = [
  {
    id: "blanc",
    name: "Blanc",
    category: "Minimal",
    description: "Quiet white space, large scannable QR, precise type.",
    config: {
      colors: {
        primary: "#14110f",
        text: "#14110f",
        background: "#ffffff",
        qr: "#14110f",
        qrBackground: "#ffffff",
        accent: "#14110f",
      },
      background: solid("#ffffff"),
      layout: {
        variant: "classic",
        padding: 9,
        qrScale: 0.46,
        gap: 5,
        contentAlign: "center",
        showStars: false,
        showFrame: false,
        frameColor: "#14110f",
        radius: 0,
      },
      qrStyle: "classic",
      businessName: typeStyle("outfit", 34, 600, "#14110f", { letterSpacing: -0.4 }),
      message: typeStyle("dm-sans", 15, 400, "#6b6560"),
      cta: typeStyle("outfit", 13, 600, "#14110f", {
        letterSpacing: 2.4,
        transform: "uppercase",
      }),
      defaultCta: "Scan to Leave a Review",
      defaultMessage: "Your feedback means a lot to us.",
    },
  },
  {
    id: "gallery",
    name: "Gallery",
    category: "Minimal",
    description: "Gallery-wall cream with a thin rule and editorial serif.",
    config: {
      colors: {
        primary: "#1c1917",
        text: "#1c1917",
        background: "#f4efe6",
        qr: "#1c1917",
        qrBackground: "#faf8f4",
        accent: "#8a8175",
      },
      background: solid("#f4efe6"),
      layout: {
        variant: "framed-center",
        padding: 10,
        qrScale: 0.42,
        gap: 4.5,
        contentAlign: "center",
        showStars: false,
        showFrame: true,
        frameColor: "#1c1917",
        radius: 0,
      },
      qrStyle: "minimal",
      businessName: typeStyle("baskerville", 36, 400, "#1c1917"),
      message: typeStyle("dm-sans", 14, 400, "#6f675c"),
      cta: typeStyle("dm-sans", 12, 500, "#1c1917", {
        letterSpacing: 3,
        transform: "uppercase",
      }),
      defaultCta: "Share Your Experience",
      defaultMessage: "Tell us about your visit.",
    },
  },
  {
    id: "noir",
    name: "Noir",
    category: "Luxury",
    description: "Ink-black field, gold rule, and restrained serif type.",
    config: {
      colors: {
        primary: "#d4b07a",
        text: "#f3ead8",
        background: "#12100e",
        qr: "#12100e",
        qrBackground: "#f3ead8",
        accent: "#d4b07a",
      },
      background: solid("#12100e", { pattern: "grain" }),
      layout: {
        variant: "framed-center",
        padding: 10,
        qrScale: 0.4,
        gap: 5,
        contentAlign: "center",
        showStars: false,
        showFrame: true,
        frameColor: "#d4b07a",
        radius: 4,
      },
      qrStyle: "elegant",
      businessName: typeStyle("fraunces", 38, 500, "#f3ead8"),
      message: typeStyle("dm-sans", 14, 400, "#cbbda4"),
      cta: typeStyle("outfit", 12, 500, "#d4b07a", {
        letterSpacing: 3.2,
        transform: "uppercase",
      }),
      defaultCta: "Your Feedback Matters",
      defaultMessage: "We would be honoured to hear from you.",
    },
  },
  {
    id: "gilded",
    name: "Gilded",
    category: "Luxury",
    description: "Charcoal suite card with ornamental corners.",
    config: {
      colors: {
        primary: "#c6a36a",
        text: "#efe6d4",
        background: "#1b1814",
        qr: "#1b1814",
        qrBackground: "#efe6d4",
        accent: "#c6a36a",
      },
      background: gradient("#1b1814", "#2a241c", 180, { pattern: "orbs" }),
      layout: {
        variant: "classic",
        padding: 11,
        qrScale: 0.38,
        gap: 5.5,
        contentAlign: "center",
        showStars: true,
        showFrame: true,
        frameColor: "#c6a36a",
        radius: 8,
      },
      qrStyle: "framed",
      businessName: typeStyle("fraunces", 36, 600, "#efe6d4"),
      message: typeStyle("baskerville", 16, 400, "#d9ccb3"),
      cta: typeStyle("outfit", 12, 600, "#c6a36a", {
        letterSpacing: 2.8,
        transform: "uppercase",
      }),
      defaultCta: "Scan & Review Us",
      defaultMessage: "A moment of your time means the world.",
    },
  },
  {
    id: "aura",
    name: "Aura",
    category: "Modern",
    description: "Soft cool gradient and contemporary geometric type.",
    config: {
      colors: {
        primary: "#1e3a5f",
        text: "#1b2430",
        background: "#e8eef7",
        qr: "#1b2430",
        qrBackground: "#ffffff",
        accent: "#3d6ea8",
      },
      background: gradient("#e4ecf8", "#f6f1ea", 135, { pattern: "orbs" }),
      layout: {
        variant: "classic",
        padding: 9,
        qrScale: 0.44,
        gap: 4.5,
        contentAlign: "center",
        showStars: false,
        showFrame: false,
        frameColor: "#1e3a5f",
        radius: 28,
      },
      qrStyle: "rounded",
      businessName: typeStyle("outfit", 33, 650, "#1b2430", { letterSpacing: -0.6 }),
      message: typeStyle("dm-sans", 15, 400, "#4d5b6c"),
      cta: typeStyle("outfit", 13, 600, "#1e3a5f"),
      defaultCta: "Scan to Leave a Review",
      defaultMessage: "Tell us about your experience.",
    },
  },
  {
    id: "frost",
    name: "Frost",
    category: "Modern",
    description: "Frosted glass panel over a quiet blue-gray field.",
    config: {
      colors: {
        primary: "#0f2744",
        text: "#102033",
        background: "#d7e1ec",
        qr: "#102033",
        qrBackground: "#f7fbff",
        accent: "#2f6f9f",
      },
      background: gradient("#cfdcea", "#eef2f6", 200, { pattern: "glass" }),
      layout: {
        variant: "framed-center",
        padding: 9,
        qrScale: 0.42,
        gap: 4,
        contentAlign: "center",
        showStars: false,
        showFrame: false,
        frameColor: "#ffffff",
        radius: 24,
      },
      qrStyle: "soft-rounded",
      businessName: typeStyle("outfit", 32, 600, "#102033"),
      message: typeStyle("dm-sans", 14, 400, "#4a5d73"),
      cta: typeStyle("outfit", 13, 600, "#0f2744"),
      defaultCta: "Share Your Experience",
      defaultMessage: "We read every review.",
    },
  },
  {
    id: "bistro",
    name: "Bistro",
    category: "Restaurant",
    description: "Wine-dark paper and cream type for dining rooms.",
    config: {
      colors: {
        primary: "#8d1e2a",
        text: "#f3e6d4",
        background: "#3b1518",
        qr: "#3b1518",
        qrBackground: "#f6ead8",
        accent: "#d4a373",
      },
      background: solid("#3b1518", { texture: "restaurant", pattern: "grain" }),
      layout: {
        variant: "footer-qr",
        padding: 10,
        qrScale: 0.4,
        gap: 4.5,
        contentAlign: "center",
        showStars: true,
        showFrame: true,
        frameColor: "#d4a373",
        radius: 6,
      },
      qrStyle: "elegant",
      businessName: typeStyle("fraunces", 38, 500, "#f3e6d4"),
      message: typeStyle("baskerville", 16, 400, "#e2c9ab"),
      cta: typeStyle("outfit", 12, 600, "#d4a373", {
        letterSpacing: 2.6,
        transform: "uppercase",
      }),
      defaultCta: "Love Our Service?",
      defaultMessage: "If you enjoyed your meal, we would love a review.",
    },
  },
  {
    id: "hearth",
    name: "Hearth",
    category: "Café",
    description: "Warm cocoa and oat — built for café counters.",
    config: {
      colors: {
        primary: "#6b3f2a",
        text: "#3a271c",
        background: "#f1e3d0",
        qr: "#3a271c",
        qrBackground: "#fffaf3",
        accent: "#a05c38",
      },
      background: gradient("#f3e4cf", "#e7d1b5", 170, {
        texture: "cafe",
        pattern: "dots",
      }),
      layout: {
        variant: "classic",
        padding: 9,
        qrScale: 0.43,
        gap: 4.5,
        contentAlign: "center",
        showStars: false,
        showFrame: false,
        frameColor: "#6b3f2a",
        radius: 22,
      },
      qrStyle: "rounded",
      businessName: typeStyle("fraunces", 36, 600, "#3a271c"),
      message: typeStyle("dm-sans", 15, 400, "#6d5344"),
      cta: typeStyle("outfit", 13, 650, "#6b3f2a"),
      defaultCta: "Tell Us What You Think",
      defaultMessage: "How was your coffee today?",
    },
  },
  {
    id: "storefront",
    name: "Storefront",
    category: "Retail",
    description: "Crisp commercial layout with a confident accent bar.",
    config: {
      colors: {
        primary: "#111111",
        text: "#111111",
        background: "#ffffff",
        qr: "#111111",
        qrBackground: "#ffffff",
        accent: "#c1121f",
      },
      background: solid("#ffffff", { texture: "retail" }),
      layout: {
        variant: "editorial",
        padding: 8.5,
        qrScale: 0.44,
        gap: 4,
        contentAlign: "left",
        showStars: false,
        showFrame: false,
        frameColor: "#111111",
        radius: 2,
      },
      qrStyle: "bold",
      businessName: typeStyle("outfit", 34, 700, "#111111", {
        align: "left",
        letterSpacing: -0.8,
      }),
      message: typeStyle("dm-sans", 15, 400, "#4b4b4b", { align: "left" }),
      cta: typeStyle("outfit", 13, 700, "#c1121f", {
        align: "left",
        transform: "uppercase",
        letterSpacing: 1.6,
      }),
      defaultCta: "Scan & Review Us",
      defaultMessage: "Thanks for shopping with us.",
    },
  },
  {
    id: "atlas",
    name: "Atlas",
    category: "Corporate",
    description: "Navy professional card for offices and firms.",
    config: {
      colors: {
        primary: "#0b1f3a",
        text: "#0b1f3a",
        background: "#f5f7fa",
        qr: "#0b1f3a",
        qrBackground: "#ffffff",
        accent: "#1f4e79",
      },
      background: solid("#f4f6f8", { texture: "office", pattern: "geometric" }),
      layout: {
        variant: "editorial",
        padding: 9,
        qrScale: 0.4,
        gap: 4,
        contentAlign: "left",
        showStars: false,
        showFrame: true,
        frameColor: "#0b1f3a",
        radius: 4,
      },
      qrStyle: "classic",
      businessName: typeStyle("dm-sans", 30, 700, "#0b1f3a", { align: "left" }),
      message: typeStyle("dm-sans", 14, 400, "#4a5565", { align: "left" }),
      cta: typeStyle("outfit", 12, 600, "#1f4e79", {
        align: "left",
        letterSpacing: 2,
        transform: "uppercase",
      }),
      defaultCta: "Your Feedback Matters",
      defaultMessage: "We value your professional feedback.",
    },
  },
  {
    id: "suite",
    name: "Suite",
    category: "Hotel",
    description: "Midnight hospitality card with gold wayfinding type.",
    config: {
      colors: {
        primary: "#c2a36b",
        text: "#f2eadb",
        background: "#151b2b",
        qr: "#151b2b",
        qrBackground: "#f2eadb",
        accent: "#c2a36b",
      },
      background: gradient("#12182a", "#1d2740", 180, {
        texture: "hotel",
        pattern: "waves",
      }),
      layout: {
        variant: "qr-hero",
        padding: 10,
        qrScale: 0.4,
        gap: 5,
        contentAlign: "center",
        showStars: true,
        showFrame: true,
        frameColor: "#c2a36b",
        radius: 10,
      },
      qrStyle: "framed",
      businessName: typeStyle("fraunces", 36, 500, "#f2eadb", { letterSpacing: 0.4 }),
      message: typeStyle("baskerville", 16, 400, "#d5cbb6"),
      cta: typeStyle("outfit", 12, 500, "#c2a36b", {
        letterSpacing: 3.4,
        transform: "uppercase",
      }),
      defaultCta: "Share Your Experience",
      defaultMessage: "We hope your stay was exceptional.",
    },
  },
  {
    id: "atelier",
    name: "Atelier",
    category: "Salon",
    description: "Blush studio card with soft serif headlines.",
    config: {
      colors: {
        primary: "#8d4a5b",
        text: "#4a2c35",
        background: "#f6e9ec",
        qr: "#4a2c35",
        qrBackground: "#fffafb",
        accent: "#c47b8a",
      },
      background: gradient("#f8ecee", "#f1ddd6", 150, {
        texture: "salon",
        pattern: "orbs",
      }),
      layout: {
        variant: "classic",
        padding: 9.5,
        qrScale: 0.41,
        gap: 4.5,
        contentAlign: "center",
        showStars: false,
        showFrame: false,
        frameColor: "#c47b8a",
        radius: 26,
      },
      qrStyle: "soft-rounded",
      businessName: typeStyle("fraunces", 36, 500, "#4a2c35"),
      message: typeStyle("dm-sans", 15, 400, "#7a5560"),
      cta: typeStyle("outfit", 13, 500, "#8d4a5b"),
      defaultCta: "Love Our Service?",
      defaultMessage: "We would love to hear how we did.",
    },
  },
  {
    id: "clinic",
    name: "Clinic",
    category: "Healthcare",
    description: "Calm clinical white with a trustworthy teal accent.",
    config: {
      colors: {
        primary: "#0f6b6b",
        text: "#17333a",
        background: "#f7fbfb",
        qr: "#17333a",
        qrBackground: "#ffffff",
        accent: "#1a8f8f",
      },
      background: solid("#f4faf9", { texture: "healthcare", pattern: "geometric" }),
      layout: {
        variant: "classic",
        padding: 9,
        qrScale: 0.42,
        gap: 4,
        contentAlign: "center",
        showStars: false,
        showFrame: false,
        frameColor: "#0f6b6b",
        radius: 16,
      },
      qrStyle: "classic",
      businessName: typeStyle("dm-sans", 30, 700, "#17333a"),
      message: typeStyle("dm-sans", 14, 400, "#4e6a70"),
      cta: typeStyle("outfit", 13, 600, "#0f6b6b"),
      defaultCta: "Your Feedback Matters",
      defaultMessage: "Help us continue to improve your care.",
    },
  },
  {
    id: "neighborhood",
    name: "Neighborhood",
    category: "Local Business",
    description: "Friendly sage card for shops around the corner.",
    config: {
      colors: {
        primary: "#2f5d3a",
        text: "#243428",
        background: "#eef4e8",
        qr: "#243428",
        qrBackground: "#ffffff",
        accent: "#4d7c55",
      },
      background: gradient("#eaf3e3", "#f6f1e4", 140, { pattern: "dots" }),
      layout: {
        variant: "classic",
        padding: 9,
        qrScale: 0.44,
        gap: 4.5,
        contentAlign: "center",
        showStars: true,
        showFrame: false,
        frameColor: "#2f5d3a",
        radius: 20,
      },
      qrStyle: "rounded",
      businessName: typeStyle("outfit", 32, 650, "#243428"),
      message: typeStyle("dm-sans", 15, 400, "#536358"),
      cta: typeStyle("outfit", 13, 650, "#2f5d3a"),
      defaultCta: "Scan to Leave a Review",
      defaultMessage: "Thanks for supporting a local business.",
    },
  },
  {
    id: "terrace",
    name: "Terrace",
    category: "Restaurant",
    description: "Sunbaked terracotta for terraces and trattorias.",
    config: {
      colors: {
        primary: "#9a3412",
        text: "#f8efe4",
        background: "#9a3412",
        qr: "#3b1c10",
        qrBackground: "#f8efe4",
        accent: "#f0d2b0",
      },
      background: gradient("#9a3412", "#7c2d12", 165, {
        texture: "restaurant",
        pattern: "waves",
      }),
      layout: {
        variant: "footer-qr",
        padding: 9.5,
        qrScale: 0.42,
        gap: 4.5,
        contentAlign: "center",
        showStars: false,
        showFrame: false,
        frameColor: "#f0d2b0",
        radius: 18,
      },
      qrStyle: "bold",
      businessName: typeStyle("fraunces", 37, 600, "#f8efe4"),
      message: typeStyle("dm-sans", 15, 400, "#f0d2b0"),
      cta: typeStyle("outfit", 13, 650, "#f8efe4", {
        letterSpacing: 1.4,
        transform: "uppercase",
      }),
      defaultCta: "Tell Us What You Think",
      defaultMessage: "We hope to see you again soon.",
    },
  },
];

export const templatesById = Object.fromEntries(
  templates.map((template) => [template.id, template]),
) as Record<string, DesignTemplate>;

export const templateCategories = [
  "Minimal",
  "Luxury",
  "Modern",
  "Restaurant",
  "Café",
  "Retail",
  "Corporate",
  "Hotel",
  "Salon",
  "Healthcare",
  "Local Business",
] as const;

export function getTemplate(id: string) {
  return templatesById[id] ?? templates[0];
}

export function createDesignFromTemplate(
  template: DesignTemplate,
  previous?: Partial<DesignState>,
): DesignState {
  return {
    templateId: template.id,
    printSize: previous?.printSize ?? "square",
    businessName: previous?.businessName ?? "Your Business",
    message: previous?.message ?? template.config.defaultMessage,
    cta: previous?.cta ?? template.config.defaultCta,
    reviewUrl: previous?.reviewUrl ?? "",
    colors: { ...template.config.colors },
    background: { ...template.config.background },
    layout: {
      showGoogleBadge: true,
      googleBadgePosition: "above-qr",
      googleBadgeStyle: "multicolor",
      ...template.config.layout,
      ...(previous?.layout ?? {}),
    },
    qrStyle: template.config.qrStyle,
    businessNameStyle: { ...template.config.businessName },
    messageStyle: { ...template.config.message },
    ctaStyle: { ...template.config.cta },
    logo: previous?.logo ?? { src: null, size: 12, position: "top" },
  };
}
